GET http://localhost:3000/aduan/


###

// Happy path testing
POST http://localhost:3000/aduan/create
Content-Type: application/json

{
  "nama_pengadu": "John Doe",
  "catatan": "Saya ingin melaporkan masalah dengan layanan Anda.",
  "kategori_aduan": "Layanan Pelanggan",
  "email": "john.doe@example.com"
}

###
// Validation testing - missing fields, expected to return 400 Bad Request
POST http://localhost:3000/aduan/create
Content-Type: application/json

{
  "nama_pengadu": "John Doe",
  "catatan": "Saya ingin melaporkan masalah dengan layanan Anda.",
  "kategori_aduan": "Layanan Pelanggan"
}
